### ISSUE TITLE
Usage not easy

### ISSUE THREAD

**Issue by flik** [testing-cabal/testtools#128]
Can I use like phpunit ?

usage of phpunit on terminal:
phpunit abc.php

**Comment by rbtcollins** [comment]
Yes:

python -m testtools abc

**Comment by flik** [comment]
I am getting this error when I try your solution:

python -m testtools test.py

/usr/bin/python: No module named testtools.__main__; 'testtools' is a package and cannot be directly executed

**Comment by rbtcollins** [comment]
Oh sorry, testtools.run :)
