### ISSUE TITLE
Tries to pull non-existent deps on python3

### ISSUE THREAD

**Issue by dobey** [testing-cabal/testtools#136]
The setup.py is declaring some setup and install deps now, including traceback2 and unittest2, which are backports of Python3 modules to Python2. This causes python3 setup.py install to fail.

**Comment by rbtcollins** [comment]
traceback2 and unittest2 are both available for 3.2,3.3,3.4. They aren't needed on 3.5 (yet) but will install ok, and will be needed once 3.6 opens. They are required for testtools on Python3 as they include 3.5 specific features. Please attach the actual error you are encountering.

**Comment by dobey** [comment]
Oh. I was not aware of that. I'm trying to get a new testtools built to see if it fixes some problems I've been having with autopilot, as the version of testtools in debian/ubuntu is incredibly far behind. So this means I will have to repackage linecache2, traceback2, and unittest2 all for python3 as well now?

**Comment by rbtcollins** [comment]
Yes, all three of those build universal wheels upstream, so should be able to use the happy-path debhelper python support to build for all pythons supported on your dpkg based distro of choice ;)

**Comment by dobey** [comment]
OK. I was able to get all these packages built for Python 3. The unittest2 package as the only one where I had a problem, as it installs usr/bin/unit2, which creates a conflict . To follow common nomenclature for packages which have scripts for both 2.x and 3.x, I renamed the 3.x version to unit2-3 for that package.
