### ISSUE TITLE
testtools 1.8 doesn't work with py2app

### ISSUE THREAD

**Issue by glyph** [testing-cabal/testtools#139]
We are rolling back to 1.7 on Mimic; see https://github.com/rackerlabs/mimic/pull/247

**Comment by glyph** [comment]
https://github.com/rackerlabs/mimic/pull/245 had the original interaction with testtools, and you can see the problematic build result here: https://travis-ci.org/rackerlabs/mimic/jobs/61387992

**Comment by rbtcollins** [comment]
I accept that this shows up with testtools 1.8, but I have no idea why. Can you produce a SSCCE ? The problematic build appears to be having a problem with distutils.

**Comment by rbtcollins** [comment]
Reading https://bitbucket.org/ronaldoussoren/py2app/issue/111/user_base-cannot-be-imported it appears clear that this is a py2app issue with setuptools/distutils and that the workarounds involved are up at the app layer, not in intermediaries like testtools is here. I'm going to close this accordingly, but if evidence to the contrary turns up, I'd be happy to help solve your issue.

**Comment by rbtcollins** [comment]
Looking in install.py:
from site import USER_BASE
from site import USER_SITE

so py2app is defining an incomplete site module.
