### ISSUE TITLE
readthedocs documentation says "testtools VERSION documentation" in the title

### ISSUE THREAD

**Issue by jml** [testing-cabal/testtools#155]
e.g. http://testtools.readthedocs.org/en/latest/index.html

"testtools: tasteful testing for Python — testtools VERSION documentation"

**Comment by jugmac00** [comment]
I can no longer reproduce the issue and I think this issue here can be closed.

**Comment by cjwatson** [comment]
Yeah, I don't know exactly how this was fixed, but it indeed doesn't seem to be an issue any more.  Closing.
