### ISSUE TITLE
Use six instead of compat

### ISSUE THREAD

**Issue by jml** [testing-cabal/testtools#160]
In #159 I suggested we drop Python 2.6. We agreed that was a bit risky for now. However, using [six](https://pypi.python.org/pypi/six) instead of testtools.compat is a great idea.

We should:
- Add six as a dependency
- Update code to use six directly instead of compat
- Deprecate compat
- Release
- Delete compat

**Comment by hugovk** [comment]
This old issue may be closed because 2.6 was dropped in https://github.com/testing-cabal/testtools/pull/198. 

(See also https://github.com/testing-cabal/testtools/pull/265 for removing some remaining redundant 2.6 code.)
