### ISSUE TITLE
assertRaises cannot be used as a context manager

### ISSUE THREAD

**Issue by dstanek** [testing-cabal/testtools#169]
Python's unittest.TestCase.assertRaises can be used as a context manager as of Python 2.7. This is nice because it makes the code much easier to read when the call being made in even moderately complicated.

The workaround is to make a new callable that wraps the complicated call, but a context manager would be preferable.

If there is no objection to this feature then I'd be happy to implement it.

**Comment by klrmn** [comment]
+1

**Comment by rbtcollins** [comment]
http://testtools.readthedocs.org/en/latest/for-test-authors.html#expectedexception

We can't easily reproduce the unittest change because we already return the exception object.
