### ISSUE TITLE
testtools.skipIf doesn't work as a class decorator

### ISSUE THREAD

**Issue by wallrj** [testing-cabal/testtools#205]
I tried decorating a `testtools.TestCase` with `testtools.skipIf` and the tests in that class still ran.

I'll try and provide a simple test to reproduce the problem.

**Comment by wallrj** [comment]
Hmm. Actually it does seem to work with the ``testtools.TestCase``. Not with ``flocker.testtools.TestCase`` so perhaps it's bug that we introduced or that has been fixed in testtools.

**Comment by jml** [comment]
See also https://bugs.launchpad.net/testtools/+bug/1529047
