### ISSUE TITLE
Example in docstring for `failed` is wrong

### ISSUE THREAD

**Issue by mithrandi** [testing-cabal/testtools#208]
The example suggests that the matcher you pass in is matched against the exception value:
```
        error = RuntimeError('foo')
        fails_at_runtime = failed(Equals(error))
        deferred = defer.fail(error)
        assert_that(deferred, fails_at_runtime)
```
However, it is actually matched against the failure. You would need to do something like this instead:
```
        error = RuntimeError('foo')
        fails_at_runtime = failed(AfterPreprocessing(lambda f: f.value, Equals(error)))
        deferred = defer.fail(error)
        assert_that(deferred, fails_at_runtime)
```
This is somewhat of an uncomfortable idiom; maybe we need an extra helper here to ease things along?

**Comment by jml** [comment]
Fixed in 725bfa9595bca9f4cd69caa21cde2d5b7b39399a

Maybe open a PR for the helper?
