### ISSUE TITLE
deferredGenerator is deprecated

### ISSUE THREAD

**Issue by mithrandi** [testing-cabal/testtools#217]
testtools/deferredruntest.py:306: DeprecationWarning: twisted.internet.defer.deferredGenerator was deprecated in Twisted 15.0.0; please use twisted.internet.defer.inlineCallbacks instead

Should be an easy enough change, I can't provide a patch at the moment so I'm just filing this so as not to forget.

**Comment by cjwatson** [comment]
This was fixed in testtools 2.2.0; belatedly closing.
