### ISSUE TITLE
Performance regression with testtools 1.9

### ISSUE THREAD

**Issue by therve** [testing-cabal/testtools#219]
I realized recently that testr got super slow.

On my repository:

> time testr last
Ran 5826 tests in 483.814s
PASSED (id=0, skips=5)

real	1m41.814s
user	1m41.197s
sys	0m0.082s

I tried a bunch of things, and finally: 

> pip install testtools==1.8.0

> time testr last
Ran 5826 tests in 483.814s
PASSED (id=0, skips=5)

real	0m20.736s
user	0m20.520s
sys	0m0.051s

So there is a giant performance regression here. I'll try to track it down, but I wanted to file the issue first.

**Comment by therve** [comment]
The issue is appearing between 1.8.1 and 1.9.0, actually.

**Comment by therve** [comment]
And I could pintpoint the issue on the changes to real.py. It seems the big refactoring to use pyrsistent is the root cause.

**Comment by jml** [comment]
Thanks. That's a shame. pyrsistent usage was deliberately kept as an
implementation detail so easy enough to fix.

I won't have an opportunity to do so though.
