### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by therve** [testing-cabal/testtools#225]
It'd be nice to have the performance regression released. Would it be possible to have a 2.1 release? Thanks.

**Comment by therve** [comment]
Bump?

**Comment by jml** [comment]
Sorry for the delay, I just got back from vacation. Things are quite hectic for me at the moment, so I personally won't be able to do a release for a little while.

**Comment by rbtcollins** [comment]
done. sorry for the delay. Would you like commit rights to help out with such things?
