### ISSUE TITLE
Circular build dependency on fixtures

### ISSUE THREAD

**Issue by pmlandwehr** [testing-cabal/testtools#236]
I've been scoping out the testing-cabal packages to make some [conda](http://conda.pydata.org/docs/) builds for [conda-forge](https://conda-forge.github.io/). In doing so, I've found what seems to be a circular dependency: `testtools` needs `fixtures >=1.3.0` which itself needs `testtools >=0.9.22`

**Comment by rbtcollins** [comment]
Thats a runtime dependency, not a build time dependency. The only build time dependency is pbr.

**Comment by rbtcollins** [comment]
Sorry, I should be more clear. Yes its circular, but that does not matter because you can build the software without loops - its only execution (such as the test suite) where there is a cycle, but wherever your installation software chooses to cut the loop will still get a valid set of packages to install.

**Comment by pmlandwehr** [comment]
Ah, cool. Got it.

**Comment by FRidh** [comment]
> Sorry, I should be more clear. Yes its circular, but that does not matter because you can build the software without loops - its only execution (such as the test suite) where there is a cycle, but wherever your installation software chooses to cut the loop will still get a valid set of packages to install.

That's bad. With Nix we have a directed acyclic graph to represent the dependencies between our packages. A package is considered a dependency if its a) a build-time dependency or b) a run-time dependency.

**Comment by rbtcollins** [comment]
That seems like Nix has attempted to over-simplify the reality of many software stacks; Compilers are great examples of systems where it is advantageous to be able to break apart the source into layers, but bringing it up de novo requires incrementally more powerful, more generally usable builds. Debian has in fact formalised this into its build system, precisely to deal with this sort of thing. https://wiki.debian.org/DebianBootstrap#Specifying_profiles.2Fstages

The case here is that we'd be artificially grouping things together, or denying ourselves the ability to use good tools, to avoid this compile-time-loop. Thats a cost we don't want, and the only benefit is working more easily for systems that over-simplify things.

**Comment by FRidh** [comment]
Well, a distinction is still made between build-time and run-time dependencies. In this case, however, our function for building `setuptools`-based Python packages adds packages that are in `install_requires` to both build-time and run-time dependencies.

Are there any rules/guidelines from setuptools that dictate that loops inside `install_requires` should be avoided? I know `pip` doesn't care about it.

**Comment by rbtcollins** [comment]
Things in setup_requires are build inputs, things in install requires are run-time, in the setuptools world.

No, theres nothing against loops in install_requires, or setup_requires, in setuptools/pip.

**Comment by cdent** [comment]
I realize this is ancient, but this cycle makes it difficult to install `fixtures` in a bazel environment.
