### ISSUE TITLE
Bad URL in repository description 

### ISSUE THREAD

**Issue by doctaphred** [testing-cabal/testtools#244]
Looks like a space character made its way into the readthedocs link in the GitHub repository description:

![screenshot 2016-12-05 12 54 08](https://cloud.githubusercontent.com/assets/3085290/20896030/f0dfb290-bae9-11e6-9619-fd8d051cfef3.png)

Link points to http://testtools.readthedocs.io/en/latest/%20 ; looks like it should be https://testtools.readthedocs.io/en/latest/ .

(May as well make it https too 🙂)

**Comment by freeekanayaka** [comment]
I believe @rbtcollins and @jml are the only ones with enough privileges to fix this.

**Comment by jml** [comment]
I've changed it to https, but I could not reproduce the '%20' behaviour.
