### ISSUE TITLE
Contains(List) matcher

### ISSUE THREAD

**Issue by manishtomar** [testing-cabal/testtools#245]
Would it make sense to add a `ContainsList` matcher similar to `ContainsDict`? I have a situation where I want to check if an element in the list conforms to a matcher which doesn't seem to be possible with current stock matchers. For example `ContainsList` can be used as
```python
>>> ContainsList([MatchesDict({"a": "b"})]).match([{"a": "b"}, {"b": "c"}])
None
``` 
I can't use `MatchesListWise` as I am concerned only about one element in the list. Maybe a better alternative would be `Contains` taking a matcher? So above can be written as
```python
>>> Contains(MatchesDict({"a": "b"})).match([{"a": "b"}, {"b": "c"}])
None
```

**Comment by freeekanayaka** [comment]
Apologies for the late reply.

It seems that if your specific use case is about just matching a single in a list and not matching a subsequence in the list, then yes, Contains() feels more appropriate and terse.

Do you have other uses cases where you'd like to have something like ContainsList?

**Comment by manishtomar** [comment]
> Apologies for the late reply.

No problem. Thanks for the reply!

> Do you have other uses cases where you'd like to have something like ContainsList?

No.

**Comment by freeekanayaka** [comment]
Closing this issue for now. It might be re-opened if folks happen to have similar uses cases.

Although I believe most of them could be admittedly be solved by combining existing matchers, we might introduce such stock convenience if it's used frequently enough.

**Comment by manishtomar** [comment]
Sorry what is the resolution? Is there going to be `Contains` that takes a matcher?
