### ISSUE TITLE
Don't use "traceback2" for CPython >= 3.5

### ISSUE THREAD

**Issue by htgoebel** [testing-cabal/testtools#246]
traceback2 is a backport of the traceback module of python 3.5 so there is no need for it in Python >= 3.5. Please change the requirements file and the import to conditionally require unittest2 only for older Python version.

Each additional package makes distribution maintainers life more complicated, since they have to maintain yet another package even if the distribution only includes Python 3.5 or even 3.6.

Thanks.

**Comment by rbtcollins** [comment]
See testing-cabal/traceback2#10
