### ISSUE TITLE
 Don't use "unittest2" for Python 3

### ISSUE THREAD

**Issue by htgoebel** [testing-cabal/testtools#247]
testtools require unittest2 for testing, but unittest2 "is no longer needed" for Python 3 (quoted from https://pypi.python.org/pypi/unittest2). Please update requirements file to conditionally require unittest2 only for older Python version.

Each additional package makes distribution maintainers life more complicated, since they have to maintain yet another package even if the distribution only includes Python 3.5 or even 3.6.

Thanks.

**Comment by rbtcollins** [comment]
See See testing-cabal/traceback2#10
