### ISSUE TITLE
as far as I can tell, the docs never tell me where to import `assert_that` from

### ISSUE THREAD

**Issue by glyph** [testing-cabal/testtools#256]
I am hoping someone will just point out where this is, but I searched http://testtools.readthedocs.io/en/latest/api.html and couldn't find it.

**Comment by freeekanayaka** [comment]
Hey Glyph,

I assume you were looking at the twistedsupport section specifically?

http://testtools.readthedocs.io/en/latest/api.html#module-testtools.twistedsupport

assert_that is defined in testtools.assertion. Would adding testtools.assertion itself to the modules with generated docs be enough to fix this issue, from your point of view?

**Comment by glyph** [comment]
@freeekanayaka Actually I wasn't really looking at the Twisted stuff here... I was just looking at the API documentation.

Yes, adding that module would probably address my concern.  On a slightly deeper reading of the docs, I can see that http://testtools.readthedocs.io/en/latest/for-test-authors.html#assert-that-function does actually say "in `testtools.assertions`", I just expected it to show up in the reference somewhere, or the code sample to `import` it.

**Comment by freeekanayaka** [comment]
@glyph Fair enough, I've added it to the API section:

http://testtools.readthedocs.io/en/latest/api.html#module-testtools.assertions
