### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by therve** [testing-cabal/testtools#260]
Hi,

This is my annual release request :). Last release was about a year ago, there are several fixes in the pipe, it'd be nice to have a new version.

Thanks!

**Comment by freeekanayaka** [comment]
Hi Thomas, I recently got the powers to do that, definitely long overdue! I'll try to do that in the next days.

**Comment by freeekanayaka** [comment]
Here you go:

https://pypi.python.org/pypi/testtools
