### ISSUE TITLE
Remove use of obsolete unittest2

### ISSUE THREAD

**Issue by exarkun** [testing-cabal/testtools#263]
From the unittest2 PyPI page:

> unittest2 is a backport of the new features added to the unittest testing framework in Python 2.7 and onwards.

testtools no longer supports Python <2.7 so there is no reason to use the backport unittest2 module.  Instead, the standard library unittest module can be used.

This would be great since unittest2 is old, crufty, and essentially unmaintained.

**Comment by mtreinish** [comment]
The wording there is a bit confusing, the "onwards" there means unittest2 is a backport lib from future versions of unittest in python stdlib. This means python3 features are backported to python2.7. Also, newer versions of python 3.x unittest are backported for older versions of 3.x. unittest2 is still needed by testtools.

**Comment by exarkun** [comment]
:cry:
