### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by mtreinish** [testing-cabal/testtools#286]
Python 2.7 is now EoL by the upstream python community. It's time to discuss dropping python 2.7 support from testtools. My feeling is we should push out a release soon with current master (and any other necessary improvements) and document that as the last release supporting python 2.7. Then remove 2.7 support from master so it's staged for the next release.

**Comment by stmcginnis** [comment]
Yes please. And Python 3.4.

I think it would make sense to do what was done in db7d6218ab7eeab53ffc5091d85c9873d5223f0c. Do a final release of the currently merged changes. Then note in the docs that anyone that needs to use EOL'd version of Python needs to use that previous release and start removing the workarounds and compatibility code in master to only target currently active versions.

**Comment by stmcginnis** [comment]
I see now https://github.com/testing-cabal/testtools/commit/05d96874bf9c971cc6d6c400306c1950e51d8b37 already dropped 3.4, it just wasn't released yet. So just continuing on that pattern. (though I think that patch should have also added the documentation of what version to use for anyone stuck on 3.4)

**Comment by hugovk** [comment]
(@stmcginnis Good point, please see PR https://github.com/testing-cabal/testtools/pull/288 to add docs about which version to use with 3.4.)

**Comment by hugovk** [comment]
Please see PR #289 for a first pass to drop support for 2.7.

**Comment by mtreinish** [comment]
#289 has merged so this can now be closed, the next testtools release (which I propose we do as 3.0.0 whenever the time is right) will no longer have 2.7 support.
