### ISSUE TITLE
circular dependency between testtools and fixtures on pypi

### ISSUE THREAD

**Issue by graingert** [testing-cabal/testtools#291]
would be better to have just one repo and distribution with both packages in as you always need them both installed

**Comment by graingert** [comment]
currently https://github.com/testing-cabal/fixtures is licenced under the BSD or Apache2 licence and https://github.com/testing-cabal/testtools/ is licenced under the MIT

All three licences are compatible and support relicensing

**Comment by cdent** [comment]
This causes issues with using testtools in an environment using bazel as the build (and install) tool. It's dependency resolver does not allow cycles.

**Comment by cdent** [comment]
Unless this can be resolved in some relatively facile way I'm going to have to pull testtools out of https://github.com/cdent/gabbi and cook my own fixtures handling.

**Comment by cjwatson** [comment]
fixtures 4.0.0 no longer depends on testtools.  It might be possible to also cause testtools not to depend on fixtures (it's already mostly optional, except for `testtools.twistedsupport`; if #327 is merged then it might make sense to add fixtures to that new extra), so I'll leave this issue option for that.

**Comment by jelmer** [comment]
fixtures support in testtools is now also optional, and only pulled in by twisted support. closing this.
