### ISSUE TITLE
Update `doc/description.rst`

### ISSUE THREAD

**Issue by jugmac00** [testing-cabal/testtools#322]
The overview on PyPI, which gets rendered via `doc/descriptions.rst`, says...

> The standard assertion methods that come with unittest aren’t as helpful as they could be, and there aren’t quite enough of them. testtools adds assertIn, assertIs, assertIsInstance and their negatives.

testools is currently Python3.5+, and the above methods were added in Python 3.1, so the statement is no longer correct.

**Comment by jelmer** [comment]
PR to fix this very welcome!
