### ISSUE TITLE
AttributeError: module 'email' has no attribute 'message'

### ISSUE THREAD

**Issue by d-kazantsev** [testing-cabal/testtools#345]
When I run unittest for my code and facing an Assertion error I got below AttributeError instead of clear information about AssertionError:
 
 File "/XXXXXXX/py3/lib/python3.10/site-packages/testtools/testresult/real.py", line 766, in _make_content_type
    msg = email.message.EmailMessage()
AttributeError: module 'email' has no attribute 'message'

I managed to solve this problem by updating real.py. I "import email.message" instead of just "import email". Could you please check/correct source code?

**Comment by jelmer** [comment]
On Thu, Jun 29, 2023 at 01:26:47AM -0700, d-kazantsev wrote:
>  When I run unittest for my code and facing an Assertion error I got below AttributeError instead of clear information about AssertionError:
>  
>  File "/XXXXXXX/py3/lib/python3.10/site-packages/testtools/testresult/real.py", line 766, in _make_content_type
>     msg = email.message.EmailMessage()
> AttributeError: module 'email' has no attribute 'message'
> 
> I managed to solve this problem by updating real.py. I "import email.message" instead of just "import email". Could you please check/correct source code?

Can you send a pull request?
