### ISSUE TITLE
Missing dependency on fixtures since 2.7.0

### ISSUE THREAD

**Issue by mariolenz** [testing-cabal/testtools#367]
I ran into a [problem](https://github.com/ansible/ansible-zuul-jobs/pull/1826#issuecomment-1798646792) because installing testtools via pip pulled in fixtures as a dependency in version 2.6.0, but doesn't since 2.7.0 (as far as I can see).

I wonder if this is intentionally or if it is a bug. It's OK if you want it to be this way, I'd just like to know. And, anyway, maybe it _is_ a bug and you're unaware of it as yet.

Would be great if you could let me know :smiley:

**Comment by jelmer** [comment]
The testtools dependency on fixtures was a private one; if you're using fixtures, you should have an explicit dependency on it if you use it. As far as I can tell, the code you're referring to isn't calling testtools but importing fixtures itself.

(please reopen if any of those are incorrect)
